/**
 * OpenAI API
 * APIs for sampling from and fine-tuning language models
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package mobi.appcent.openai.models


/**
 * 
 * @param role The role of the author of this message.
 * @param content The contents of the message
 */
data class ChatCompletionResponseMessage (
    /* The role of the author of this message. */
    val role: String,
    /* The contents of the message */
    val content: String
)