/**
 * OpenAI API
 * APIs for sampling from and fine-tuning language models
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package mobi.appcent.openai.models

/**
 * 
 * @param text 
 * @param index 
 * @param logprobs 
 * @param finishReason 
 */
data class CreateCompletionResponseChoices (

    val text: kotlin.String? = null,
    val index: kotlin.Int? = null,
    val logprobs: CreateCompletionResponseLogprobs? = null,
    val finishReason: kotlin.String? = null
) {
}