/**
 * OpenAI API
 * APIs for sampling from and fine-tuning language models
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package mobi.appcent.openai.models


/**
 * 
 * @param hate 
 * @param hateSlashthreatening 
 * @param selfHarm 
 * @param sexual 
 * @param sexualSlashminors 
 * @param violence 
 * @param violenceSlashgraphic 
 */
data class CreateModerationResponseCategories (

    val hate: kotlin.Boolean,
    val hateSlashthreatening: kotlin.Boolean,
    val selfHarm: kotlin.Boolean,
    val sexual: kotlin.Boolean,
    val sexualSlashminors: kotlin.Boolean,
    val violence: kotlin.Boolean,
    val violenceSlashgraphic: kotlin.Boolean
) {
}