/**
 * OpenAI API
 * APIs for sampling from and fine-tuning language models
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package mobi.appcent.openai.models


/**
 * 
 * @param query Query to search against the documents.
 * @param documents Up to 200 documents to search over, provided as a list of strings.  The maximum document length (in tokens) is 2034 minus the number of tokens in the query.  You should specify either `documents` or a `file`, but not both. 
 * @param file The ID of an uploaded file that contains documents to search over.  You should specify either `documents` or a `file`, but not both. 
 * @param maxRerank The maximum number of documents to be re-ranked and returned by search.  This flag only takes effect when `file` is set. 
 * @param returnMetadata A special boolean flag for showing metadata. If set to `true`, each document entry in the returned JSON will contain a \"metadata\" field.  This flag only takes effect when `file` is set. 
 * @param user A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn more](/docs/guides/safety-best-practices/end-user-ids). 
 */
data class CreateSearchRequest (

    /* Query to search against the documents. */
    val query: kotlin.String,
    /* Up to 200 documents to search over, provided as a list of strings.  The maximum document length (in tokens) is 2034 minus the number of tokens in the query.  You should specify either `documents` or a `file`, but not both.  */
    val documents: kotlin.Array<kotlin.String>? = null,
    /* The ID of an uploaded file that contains documents to search over.  You should specify either `documents` or a `file`, but not both.  */
    val file: kotlin.String? = null,
    /* The maximum number of documents to be re-ranked and returned by search.  This flag only takes effect when `file` is set.  */
    val maxRerank: kotlin.Int? = null,
    /* A special boolean flag for showing metadata. If set to `true`, each document entry in the returned JSON will contain a \"metadata\" field.  This flag only takes effect when `file` is set.  */
    val returnMetadata: kotlin.Boolean? = null,
    /* A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn more](/docs/guides/safety-best-practices/end-user-ids).  */
    val user: kotlin.String? = null
) {
}