/**
 * OpenAI API
 * APIs for sampling from and fine-tuning language models
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package mobi.appcent.openai.models


/**
 * 
 * @param hate 
 * @param hateSlashthreatening 
 * @param selfHarm 
 * @param sexual 
 * @param sexualSlashminors 
 * @param violence 
 * @param violenceSlashgraphic 
 */
data class CreateModerationResponseCategoryScores (

    val hate: java.math.BigDecimal,
    val hateSlashthreatening: java.math.BigDecimal,
    val selfHarm: java.math.BigDecimal,
    val sexual: java.math.BigDecimal,
    val sexualSlashminors: java.math.BigDecimal,
    val violence: java.math.BigDecimal,
    val violenceSlashgraphic: java.math.BigDecimal
) {
}