/**
 * OpenAI API
 * APIs for sampling from and fine-tuning language models
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package mobi.appcent.openai.models

/**
 * 
 * @param id 
 * @param model 
 * @param results 
 */
data class CreateModerationResponse (

    val id: kotlin.String,
    val model: kotlin.String,
    val results: kotlin.Array<CreateModerationResponseResults>
) {
}