/**
 * OpenAI API
 * APIs for sampling from and fine-tuning language models
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package mobi.appcent.openai.models


/**
 * 
 * @param file The audio file to translate, in one of these formats: mp3, mp4, mpeg, mpga, m4a, wav, or webm. 
 * @param model ID of the model to use. Only `whisper-1` is currently available. 
 * @param prompt An optional text to guide the model's style or continue a previous audio segment. The [prompt](/docs/guides/speech-to-text/prompting) should be in English. 
 * @param responseFormat The format of the transcript output, in one of these options: json, text, srt, verbose_json, or vtt. 
 * @param temperature The sampling temperature, between 0 and 1. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic. If set to 0, the model will use [log probability](https://en.wikipedia.org/wiki/Log_probability) to automatically increase the temperature until certain thresholds are hit. 
 */
data class CreateTranslationRequest (

    /* The audio file to translate, in one of these formats: mp3, mp4, mpeg, mpga, m4a, wav, or webm.  */
    val file: kotlin.Array<kotlin.Byte>,
    /* ID of the model to use. Only `whisper-1` is currently available.  */
    val model: kotlin.String,
    /* An optional text to guide the model's style or continue a previous audio segment. The [prompt](/docs/guides/speech-to-text/prompting) should be in English.  */
    val prompt: kotlin.String? = null,
    /* The format of the transcript output, in one of these options: json, text, srt, verbose_json, or vtt.  */
    val responseFormat: kotlin.String? = null,
    /* The sampling temperature, between 0 and 1. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic. If set to 0, the model will use [log probability](https://en.wikipedia.org/wiki/Log_probability) to automatically increase the temperature until certain thresholds are hit.  */
    val temperature: java.math.BigDecimal? = null
) {
}