/**
 * OpenAI API
 * APIs for sampling from and fine-tuning language models
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package mobi.appcent.openai.models


/**
 * 
 * @param tokens 
 * @param tokenLogprobs 
 * @param topLogprobs 
 * @param textOffset 
 */
data class CreateCompletionResponseLogprobs (

    val tokens: kotlin.Array<kotlin.String>? = null,
    val tokenLogprobs: kotlin.Array<java.math.BigDecimal>? = null,
    val topLogprobs: kotlin.Array<kotlin.Any>? = null,
    val textOffset: kotlin.Array<kotlin.Int>? = null
) {
}