/**
 * OpenAI API
 * APIs for sampling from and fine-tuning language models
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package mobi.appcent.openai.models

/**
 * 
 * @param id 
 * @param &#x60;object&#x60; 
 * @param createdAt 
 * @param updatedAt 
 * @param model 
 * @param fineTunedModel 
 * @param organizationId 
 * @param status 
 * @param hyperparams 
 * @param trainingFiles 
 * @param validationFiles 
 * @param resultFiles 
 * @param events 
 */
data class FineTune (

    val id: kotlin.String,
    val `object`: kotlin.String,
    val createdAt: kotlin.Int,
    val updatedAt: kotlin.Int,
    val model: kotlin.String,
    val fineTunedModel: kotlin.String,
    val organizationId: kotlin.String,
    val status: kotlin.String,
    val hyperparams: kotlin.Any,
    val trainingFiles: kotlin.Array<OpenAIFile>,
    val validationFiles: kotlin.Array<OpenAIFile>,
    val resultFiles: kotlin.Array<OpenAIFile>,
    val events: kotlin.Array<FineTuneEvent>? = null
) {
}