name: Publish package to GitHub Packages
on:
  push:
    branches:
      - 'release/**'
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v3
          with:
            java-version: '11'
            distribution: 'adopt'
        - name: Validate Gradle wrapper
          uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
        - name: Checkout code
          uses: actions/checkout@v1
        - name: Setup JDK 11
          uses: actions/setup-java@v1
          with:
            java-version: 11
        - name: Make Gradle executable
          run: chmod +x ./gradlew
        - name: Create Release ✅
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.ref_name }}
            release_name: ${{ github.ref_name }}
            draft: false
            prerelease: false


